# Connection Settings
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.ycaxiqomnuwjfboeihbp
spring.datasource.password=JamesCotiangco

# Driver Class
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool Settings (HikariCP defaults)
spring.datasource.hikari.maximum-pool-size=10

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
